### ISSUE TITLE
Error during Make

### ISSUE THREAD

**Issue by rajatserc** [It4innovations/Maui-Simulation#2]
Hello,
I am a System-admin from Supercomputer Education and Research Centre at Bangalore India,
I was trying to use the Maui Simulator but I have ran into an issue during make of maui installation:
 
-------------------------------------------------------------------------------------------------------------------------

gcc -I../../include/ -I/usr/local/maui/include     -I/opt/pbs/include -D__LINUX   -D__MPBS        -g -O2 -D__M64  -c MPBSI.c
MPBSI.c: In function ‘MPBSInitialize’:
MPBSI.c:377:7: error: ‘PBS_SCHEDULER_SERVICE_NAME’ undeclared (first use in this function)
       PBS_SCHEDULER_SERVICE_NAME,
       ^
MPBSI.c:377:7: note: each undeclared identifier is reported only once for each function it appears in
MPBSI.c:379:7: error: ‘PBS_SCHEDULER_SERVICE_PORT’ undeclared (first use in this function)
       PBS_SCHEDULER_SERVICE_PORT);     
       ^
MPBSI.c: In function ‘__MPBSGetNodeState’:
MPBSI.c:1789:28: error: ‘ND_down’ undeclared (first use in this function)
       if (strstr(AP->value,ND_down) || strstr(AP->value,ND_state_unknown))
                            ^
MPBSI.c:1789:57: error: ‘ND_state_unknown’ undeclared (first use in this function)
       if (strstr(AP->value,ND_down) || strstr(AP->value,ND_state_unknown))
                                                         ^
MPBSI.c:1793:33: error: ‘ND_offline’ undeclared (first use in this function)
       else if (strstr(AP->value,ND_offline))
                                 ^
MPBSI.c:1801:33: error: ‘ND_free’ undeclared (first use in this function)
       else if (strstr(AP->value,ND_free))
                                 ^
MPBSI.c:1805:33: error: ‘ND_job_exclusive’ undeclared (first use in this function)
       else if (strstr(AP->value,ND_job_exclusive))
                                 ^
MPBSI.c:1809:33: error: ‘ND_busy’ undeclared (first use in this function)
       else if (strstr(AP->value,ND_busy))
                                 ^
MPBSI.c:1815:33: error: ‘ND_job_sharing’ undeclared (first use in this function)
       else if (strstr(AP->value,ND_job_sharing))
                                 ^
make[1]: *** [MPBSI.o] Error 1

-------------------------------------------------------------------------------------------------------------------------

Requesting your assistance with this issue.
Thanks in advance!

**Comment by gzitzlsb-it4i** [comment]
Hello,

I can confirm the problem and updated the repository. Git versions of PBS and Maui are pinned now. Also a missing header has been added.
At this occasion, I've also improved the description of how to use the simulation environment.

Thank you for reporting & best regards,

Georg Zitzlsberger
