### ISSUE TITLE
Issue with building docker image

### ISSUE THREAD

**Issue by rajatserc** [It4innovations/Maui-Simulation#3]
Hi,
I am getting the following error duing docker build:
Cloning into 'maui'...
fatal: unable to access 'https://github.com/LabAdvComp/maui.git/': Could not resolve host: github.com

And I also had a question, can maui_sched be replaced with pbs_sched in this simulator?

**Comment by gzitzlsb-it4i** [comment]
Hello,

that's interesting - the Github repo from MAUI was removed and the entire LabAdvComp account has no repositories any more. It also looks like there was a change of owners. I found the source code also here:
- https://github.com/TempleHPC/maui-scheduler
- https://github.com/mfagiani/maui

However, the branch does not exist as such. You might be able to use these as alternative as the simulator in MAUI wasn't changed that frequently.
Please let me know if any one of these work. Simply replace the "git clone" URL and drop the "checkout <branch #>".

To my knowledge, it is not possible to replace the scheduler in the simulator. You can do it the other way around, in using the MAUI scheduler in PBS, though.

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
Thanks for your reply.
Will try it out and let you know.

**Comment by gzitzlsb-it4i** [comment]
Great, thank you! Please let me know if it works. In case there are some problems I might find the time later this week to have a look.
In case you confirm it working, I'll update the Dockerfile. I think I'll also fork the code, just in case.

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
I used the following link for "git clone" and the build was successful:
[https://github.com/mfagiani/maui](url)

However, when I execute the command mentioned in step 3, "/usr/local/maui/sbin/maui --host=mauisim &", I get the following error:
starting 3.3.1 version Maui (PID: 24) on Thu Dec  3 11:13:53
WARNING:  cannot open statfile '/home/hpcacct/workdir/stats/simstat.out', errno: 2 (No such file or directory)

The "stats" folder does not exist in workdir/

Regards,
Rajat

**Comment by gzitzlsb-it4i** [comment]
Hello Rajat,

if I remember correctly, the "stats" folder needs to be created manually. Can you create it as empty folder and run again?

Thank you very much for confirming that the other repository works! I'll update the Dockerfile soon.

Georg

**Comment by gzitzlsb-it4i** [comment]
Hello Rajat,

thanks to your help, I've updated the Dockerfile. I also checked that the error with the stats directory goes away once you create it (mkdir stats).
I'll close the ticket now. Please feel free to reopen in case it still does not work.

Best regards,

Georg

Edit:
As you might have seen already, I've forked the repo now as well so we're not dependent on external sources anymore. I've also put the empty "stats" directory now into the project to avoid the error writing "stats/simstat.out".

**Comment by rajatserc** [comment]
Hello Georg,
Apologies on the late reply. 
I was getting the permission denied error for "stats/simstat.out". However, I added the user to sudoers group and changed ownership of "workdir/" to the user.

Regards,
Rajat
