### ISSUE TITLE
No output written to simstat.out

### ISSUE THREAD

**Issue by rajatserc** [It4innovations/Maui-Simulation#4]
Hello Georg,
After running "/usr/local/maui/sbin/maui --host=mauisim &" and then "showstats" it mentions that there are two jobs, one active and another, idle.
The state does not change regardless of the duration it is running. And there is not output written to simstat.out.

Could you please help me with running the simulation and getting proper output?

I work on Cray XC-40 system which is not partitioned. I would like to know how to run simulations for an un-partitioned system using this simulator.

And, could you also provide more information on the "Resource.Trace1" and "Workload.Trace_example" files? For example, headers for contents in the files.

Regards,
Rajat

**Comment by gzitzlsb-it4i** [comment]
Hello Rajat,

did you take a look at the control_example.sh? It might look a bit convoluted, but it shows how we ran the simulator through the different time steps.
If you just start and check the status, there is only the initial state. You need to advance the simulation time step. In the control_example.sh I've used the epoch (1486539500) from the first job submitted (initial state of the simulator) as a reference and then progress only event by event. Events are setting/freeing reservations to simulate also node/system downtime in our case.
If you did not see any outputs in simstat, that means that no jobs have completed yet, i.e. you advanced the simulation not far enough for the first job(s) to terminate.
I'd suggest to run the control_example.sh right after you started up MAUI. That definitely should leave results.

For the trace file format documentation please refer to the MAUI documentation:
http://docs.adaptivecomputing.com/maui/trace.php

Best regards,

Georg

**Comment by rajatserc** [comment]
Hello Georg,
Thanks for your response!
I had not exported HOST and PORT variables for running control_example.sh. 
It is working now!

Regards,
Rajat
